### ISSUE TITLE
Adding a custom homepage?

### ISSUE THREAD

**Issue by CodeRunner00** [carlos-algms/hexo-theme-materialize#1]
Hi, Carlos!  Awesome portfolio/blog theme.  I am wondering how you were able to add all of the information about your Javascript skills and projects to the home page using this theme?  When I add an index.html file to the source folder of my blog nothing is displayed.  Thank you, Eric

**Comment by carlos-algms** [comment]
Hi Eric, thanks for using my theme, I'm glad you liked it.

Try to add this as the first lines of you `index.html` :

```
---
layout: index
title:
comments: false
---
```

Take a look at my files structure: 

![image](https://cloud.githubusercontent.com/assets/4634613/25559158/575738d8-2d0c-11e7-8342-5bfa0bd9a012.png)

**Comment by carlos-algms** [comment]
And please, let me know if it worked and share your site URL.

**Comment by CodeRunner00** [comment]
Thanks for the detailed response.

I did add the layout, title, and comments properties before.  I tried changing the layout property to index.ejs but that did not fix it.  I also had the index.html file in the source directory under my blog's root directory.  

I have some familiarity with ejs and found that when I added the html right onto index.ejs in the materialize theme's source directory it displayed on the screen.  Do you have a controller that displays the content of the layout index on the page?  Thank you, Eric

**Comment by carlos-algms** [comment]
@CodeRunner00, I double checked my configs and the only thing that makes sense is add this to your 
`_config.yml` :

```yml
theme: materialize
exclude_generators:
- index
```

**Comment by carlos-algms** [comment]
Actually, what is happening for you ? Because there is no controllers at all. Everything is static and the files can be even .html or .md

As you can see here:
https://github.com/carlos-algms/carlos-algms.github.io/tree/source/source

Hexo will handle the .ejs files, those files exists on the theme folder because Hexe needs to process it, you should not change files under themes forlder.

The layout property should be `index` without extension.

**Comment by CodeRunner00** [comment]
Thank you.

I resolved this issue with 
> npm remove hexo-generator-index

**Comment by carlos-algms** [comment]
Good to know!!!! 
Please, Share your site I really want to see what you developed!!

**Comment by CodeRunner00** [comment]
Sure thing!  I will once I've got everything up and running.

**Comment by CodeRunner00** [comment]
Here is my blog.  Still have a bit to go but it's up and running!  
https://coderunner00.github.io/

**Comment by carlos-algms** [comment]
Congrats. 

O saw that your code blocks are not getting highlighted, try to write ` ` ` javascript 
(spaces to avoid github process it)

**Comment by carlos-algms** [comment]
failed miserably, :)

use 3 backticks then write javascript, should work
