### ISSUE TITLE
Carousel not working

### ISSUE THREAD

**Issue by moranil** [carlos-algms/hexo-theme-materialize#3]
Hi,
I was adding Carousel to the index page. as defined here: http://materializecss.com/carousel.html

source/index.html:
```
<div class="carousel carousel-slider center" data-indicators="true">
    <div class="carousel-fixed-item center">
      <a class="btn waves-effect white grey-text darken-text-2">button</a>
    </div>
    <div class="carousel-item red white-text" href="#one!">
      <h2>First Panel</h2>
      <p class="white-text">This is your first panel</p>
    </div>
    <div class="carousel-item amber white-text" href="#two!">
      <h2>Second Panel</h2>
      <p class="white-text">This is your second panel</p>
    </div>
    <div class="carousel-item green white-text" href="#three!">
      <h2>Third Panel</h2>
      <p class="white-text">This is your third panel</p>
    </div>
    <div class="carousel-item blue white-text" href="#four!">
      <h2>Fourth Panel</h2>
      <p class="white-text">This is your fourth panel</p>
    </div>
  </div>


<script type="text/javascript">

     $(document).ready(function(){
      console.log("logs");     
     // $('.carousel').carousel();
      $('.carousel.carousel-slider').carousel({fullWidth: true});

      setInterval(function(){
         $('.carousel').carousel('next'); // Move next n times.
       }, 3000);    
    });  
</script>
```

It shows nothing. 
When I add materialize css,js to the layout.ejs, it works but on console it shows many error, probably because of duplication of lib included. 

added following lines to layout.ejs 
```
......
  <%- js('js/vendors') %>

   <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.2/css/materialize.min.css">

  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.2/js/materialize.min.js"></script>
          
 

```

**Comment by moranil** [comment]
Hi,
Could it be because theme does not uses the latest version of materialize css. 
Can I have the latest lib to be included in the theme?
or How can I compile theme with the latest materialize?
Please help me solve this issue.

**Comment by moranil** [comment]
Hi,
I can confirm that updating materialize css to latest version fixed the issue

in package.json change 
`
"materialize-css": "^0.98.2",

`
then rebuild the theme
`
grunt build

`

replaced the source directory of the my hexo projects theme that is
/themes/materialize/source

and it worked.

the only issue is, in mobile view, the nav bar is too much grey.. see image attached

![screencapture-localhost-4000-1494248282024](https://cloud.githubusercontent.com/assets/1230470/25805177/5ffcd9f4-341c-11e7-952e-61641860b5bc.png)

**Comment by carlos-algms** [comment]
Sorry for the delay, busy week. 
I will try to update the deps.

But you can try to run `npm upgrade` under the theme folder.

**Comment by moranil** [comment]
fixed the side bar grey issue:

in header.ejs, moved the code out of nav div
```

<div class="navbar-fixed">
  <nav id="main-navbar" class="grey lighten-5 z-depth-0" role="navigation">
    <div class="nav-wrapper container">

      <a id="logo-container" href="<%- url_for() %>" class="brand-logo center-align">
        <img class="example-icon md-card-image" height="32px" src="/images/logo3.png" /> 
      <!--  <span><%= config.title %></span> -->
        <sub><%= config.subtitle %></sub>
      </a>

      <ul class="right hide-on-med-and-down">
        <% for (var i in theme.menu){ %>
          <li>
            <a class="main-nav-link" href="<%- url_for(theme.menu[i]) %>"><%= i %></a>
          </li>
        <% } %>
      </ul>      
      <a href="#" data-activates="nav-mobile" class="button-collapse">
        <i class="material-icons">menu</i>
      </a>
    </div>
  </nav>
</div>
<ul id="nav-mobile" class="side-nav">
        <li><a href="#">Navbar Link</a></li>
</ul>

```

![screencapture-localhost-4000-1494249961784](https://cloud.githubusercontent.com/assets/1230470/25806232/2f8575e8-3420-11e7-881e-57c6a38cedf7.png)

**Comment by carlos-algms** [comment]
Thanks for the support, fixed now.
Please see #4 and #5
